export { default as Books } from './Books'
export { default as Tools } from './Tools'
export { default as Chatbot } from './Chatbot'
export { default as ToolUsage } from './ToolUsage'
export { default as Dashboard } from './dashboard'
export { default as ProfileDetails } from './Details'
export { default as Contact } from './Contact'
export { default as Plans } from './Plans'
export { default as Usage } from './Usage'

export { default as Register } from './auth/register'
export { default as Login } from './auth/login'
export { default as Verify } from './auth/verify'
export { default as SelectCategory } from './auth/category'
export { default as Reset } from './auth/reset'
export { default as NewPassword } from './auth/newpassword'

export { default as AdminBooks } from './admin/books'
export { default as AdminCategories } from './admin/categories'
export { default as AdminSubcategories } from './admin/subcategories'
export { default as AdminPlans } from './admin/plans'
export { default as AdminTools } from './admin/tools'
export { default as AdminMessages } from './admin/messages'